### ISSUE TITLE
Booking Flow- Frontend

### ISSUE THREAD

**Issue by kshtjfuel** [Fuel-DAO/fuel-dao-leptos-ssr#1]
Here's the design file- https://www.figma.com/design/ZEUQPdQlBjWnjJugU60XRd/Fuel-Dao-Website?node-id=313-34477&node-type=canvas&t=RXgNtx5QYH7xGajG-0.

Here's the PRD- https://www.notion.so/gobazzinga/PRD-Rental-Car-Booking-bae88b880cf84d52b9a32f96374e4a9b

The booking flow frontend consists of the following key components-

[Home Page](https://github.com/orgs/Fuel-DAO/projects/4/views/1?pane=issue&itemId=80913774): 

1. Calendar + time picker for date & time combination for both pickup & dropoff respectively.
2. Location picker- It will look like a search bar, but clicking on it will only give one hard-coded result- "Bangalore".
3. Search button. Clicking this will go to the results page.

[Results page](https://github.com/orgs/Fuel-DAO/projects/4/views/1?pane=issue&itemId=80913781):

1. If it's available, we'll have just the one car card shown.
2. If it's not available, we'll show text saying 'Car not available'. Exact copy is available in the design file.

[Car card on results page](https://github.com/orgs/Fuel-DAO/projects/4/views/1?pane=issue&itemId=80913791): 

1. Fields- Car Name, Car Type, Image, Steering, True Range, Fuel Type, Seater.
2. Inside the car card, fields- Car name, 3 images, Description, Fuel type, Car type, Capacity, Steering, True Range, Price, 'Rent Now' button.
3. We'll only have one car available in the start. Display a price cut from Rs. 6000/day to Rs. 4000 per day. This price can be hard-coded.

**Comment by prakash-bhatt-fuel** [comment]
- [ ] Show search result
- [ ] Show popup for car on click
